
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/storage/pace-apps/spack/packages/linux-rhel9-x86_64_v3/gcc-11.3.1/cmake-3.26.3-cdybay2vek24wxrgh2xno2kdcy3uphs6/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Linux - 5.14.0-362.13.1.el9_3.x86_64 - x86_64
...
